services:
  minerva:
    image: minerva:latest
    container_name: minerva
    ports:
      - "10101:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Minio__Endpoint=46.253.143.48:9000
      - Minio__AccessKey=LightAndStyx
      - Minio__SecretKey=LightAndStyxYSECRETKEYfffRRR
      - Minio__UseSsl=false
    restart: unless-stopped