services:
  minerva:
    image: minerva:latest
    container_name: minerva
    ports:
      - "10101:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AWS__Profile=rustfs
      - AWS__Region=us-east-1
      - AWS__ServiceURL=http://<domen>:<port>
      - AWS__AccessKey=<login>
      - AWS__SecretKey=<password>
      - AWS__UseHttp=false # Использовать https (tls) или нет
      - AWS__ForcePathStyle=true
    restart: unless-stopped